name: Notify on PR Merges

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

env:
  TARGET_REPO: "runelite/plugin-hub"
  TARGET_AUTHOR: "SuperNerdEric"
  MESSAGE_PREFIX: "📢 Combat Logger has updated on the RuneLite Plugin Hub!"
  FOOTER_NOTE: "You may need to restart your RuneLite in order to receive the update."
  TIMEZONE: "America/New_York"
  TRACKER_FILE: ".pr-tracker/reported.txt"
  COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
  COMMIT_NAME: "GitHub Actions"

jobs:
  check-merged-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure tracking file exists
        run: |
          mkdir -p $(dirname "$TRACKER_FILE")
          touch "$TRACKER_FILE"

      - name: Fetch and process merged PRs
        run: |
          echo "Checking for merged PRs by $TARGET_AUTHOR in $TARGET_REPO..."

          OWNER=$(echo "$TARGET_REPO" | cut -d/ -f1)
          REPO=$(echo "$TARGET_REPO" | cut -d/ -f2)

          curl -s "https://api.github.com/repos/$OWNER/$REPO/pulls?state=closed" \
          | jq -r --arg author "$TARGET_AUTHOR" '.[] | select(.user.login == $author and .merged_at != null) | "\(.number)\t\(.title)\t\(.body)\t\(.html_url)\t\(.merged_at)"' > merged.txt

          reported_new=false

          if [[ -s merged.txt ]]; then
            echo "Found merged PR(s):"
            cat merged.txt

            while IFS=$'\t' read -r number title body url merged_at; do
              if grep -q "^$number$" "$TRACKER_FILE"; then
                echo "Already reported PR #$number"
                continue
              fi

              echo "Reporting PR #$number"
          
              prefix_with_url="${MESSAGE_PREFIX} <${url}>"
          
              payload=$(jq -n \
                --arg prefix "$prefix_with_url" \
                --arg title "$title" \
                --arg body "$body" \
                --arg footer "$FOOTER_NOTE" \
                '{content: ($prefix + "\n\n**" + $title + "**\n" + $body + "\n\n" + $footer)}')
              curl -X POST -H "Content-Type: application/json" -d "$payload" ${{ secrets.DISCORD_WEBHOOK }}

              echo "$number" >> "$TRACKER_FILE"
              reported_new=true
            done < merged.txt
          else
            echo "No merged PRs by $TARGET_AUTHOR found."
          fi

          if [[ "$reported_new" = true ]]; then
            git config user.email "$COMMIT_EMAIL"
            git config user.name "$COMMIT_NAME"
            git add "$TRACKER_FILE"
            git commit -m "Track new reported PRs [skip ci]"
            git push
          else
            echo "No new PRs to report or commit."
          fi

        env:
          TZ: ${{ env.TIMEZONE }}
